- assets/grocery_crud/js/jquery_plugins/config/jquery-ui-timepicker-addon.config.js
- assets/grocery_crud/js/jquery_plugins/config/jquery.datetime.config.js
Fixed problem with Event Creation in Admin cousing not being able to
choose a PM hour (12 vs 24 hour clocks)
> Fixing Event Creation Bug #141

- application/controllers/assignments.php
- application/controllers/demerits.php
> ToS cut off at GD

- application/config/routes.php
- application/controllers/assignments.php
- application/controllers/qualifications.php
- application/controllers/units.php
- application/models/discharge_model.php
- application/models/member_model.php
- application/models/qualification_model.php
For 29th/personnel#231
Update to make scripts updating squad tags in gameservers return correct unit (used to return LH, Adj, etc).
In L:82 if you set `ORDER BY` to `class ASC, path ASC` you get a top combat assignment, if set to `class ASC, path DESC`  you get a lowest combat assignment
> memeber list (for gameserver ini feeding)

- application/controllers/attendance.php
- application/models/attendance_model.php
- application/models/recruits_model.php
modified:   application/models/recruits_model.php
> Changing recruit count to include only Accepted enlistments

- application/controllers/alerts.php
- application/controllers/attendance.php
- application/controllers/finances.php
- application/controllers/units.php
- application/models/attendance_model.php
- Showing more info on finance ledger
- Tweaking Enlistments
> Finance and enlistments fixes (api)

- application/config/routes.php
- application/controllers/tps.php
- application/models/assignment_model.php
- application/models/enlistment_model.php
- application/models/tp_model.php
- Added TPs view API
- Changes on enlistment list
> TPs and enlistments

- application/controllers/banlogs.php
- application/models/banlog_model.php
- application/models/member_model.php
1. Adding BanLogs from front end (for people with right permissions)
2. Changed sorting of memberlist
> Banlog adding

- application/controllers/enlistments.php
- application/controllers/members.php
- application/controllers/tps.php
- application/controllers/units.php
- application/models/assignment_model.php
- application/models/tp_model.php
* Processing Enlistment now shows dates on TPs' list
* Only ELs show up on Liaison list in Processing Enlistment
* More information on members in Member Search
* Changing status of enlistment closes assignment instead of deleting it
> Enlistments and TPs

- application/controllers/admin.php
- application/models/assignment_model.php
- application/models/banlog_model.php
- Changes for graphical roster
- fix in banlog
> Graphical Roster

- application/controllers/admin.php
- application/controllers/units.php
1. Data for qualifications view
2. Changes in API/Admin
> Qualifications +

- application/controllers/awardings.php
- application/libraries/User.php
- application/models/assignment_model.php
- application/models/awarding_model.php
- application/models/event_model.php
- application/models/member_model.php
- application/models/tp_model.php
- list of drills for user
- added list of badges (awards with game <> 'N/A') per member
- added avg of attendance for TPS
> Drills list! + others

- application/controllers/units.php
- application/libraries/User.php
- application/models/event_model.php
* ELOAs in unit's `stats` tab
* User's `Drills` tab now includes color-coded references to attendance and LOAs
* User's `Drills` tab includes drills for all user's assginments, not only main one
> Drills, stats

- application/controllers/tps.php
- application/libraries/servicecoat.php
- application/models/awarding_model.php
* New awards added to service jacket
* Additional info on recruiter in TP
> TP, servicecoat

- application/libraries/servicecoat.php
- Added Pilot Badge
- Fixed size of font on name tag for longer last names
- Added shoulder insignia for Warrent Officers 
- Added AQB for RS Armor
> Service coat fixes

- application/controllers/enlistments.php
- application/libraries/Vanilla.php
- application/models/banlog_model.php
- application/models/member_model.php
- Additional info in enlistment processing:
- e-mail
- IPs in forums
- Mentions in banlogs
- Other people with that name
- Banlogs searchable by IP
> Additional info in enlistment processing

- application/controllers/discharges.php
- application/libraries/Vanilla.php
New forums name generation (for non-members).
Update of forum name and service coat image upon discharge
> Forum names

- application/controllers/assignments.php
- application/controllers/enlistments.php
- Forum name updated on new assignment
- Forum name updated on processing enlistment
- Fix for bug leaving past assignment when switching TPs on already accepted enlistment
> Updating names; Fixing assigments to TPs

- application/controllers/members.php
> Sigs update

- application/controllers/admin.php
- application/controllers/alerts.php
- application/controllers/assignments.php
- application/controllers/events.php
- application/controllers/tps.php
- application/controllers/units.php
- application/libraries/Forum.php
- application/models/alerts_model.php
- application/models/assignment_model.php
- application/models/attendance_model.php
- application/models/event_model.php
- application/models/member_model.php
- application/models/tp_model.php
- application/models/unit_model.php
To be compatible with https://github.com/29th/personnel-v3/commit/933dae1eab4bee9ee1d39deff0b43deedd47b9e3
See 29th/personnel#524
> Rename units.class to classification

- application/controllers/enlistments.php
> Rename units to previous units on enlistments, and serialize it as an array of objects
